version: 1.0.{build}
image: Visual Studio 2019 Preview
configuration: Release
before_build:
- ps: dotnet restore
after_build:
- ps: dotnet pack -c release
build:
  verbosity: minimal
test_script:
- ps: dotnet test .\Divergic.Logging.Xunit.UnitTests\Divergic.Logging.Xunit.UnitTests.csproj
artifacts:
- path: '**\*.nupkg'
